swagger: "2.0"
info:
  description: "WM Tippspiel"
  version: "1.0.0"
  title: "WM Tippspiel"
host: "wodss-tippspiel-api.herokuapp.com"
basePath: "/api"
tags:
- name: "meta"
  description: "Operations about auth"
- name: "auth"
  description: "Operations about auth"
- name: "users"
  description: "Operations about user"
- name: "teams"
  description: "Operations about team"
- name: "games"
  description: "Operations about games"
- name: "ranking"
  description: "Operations about rankings"
schemes:
- "https"
securityDefinitions:
  basicAuth:
    type: basic
  bearerAuth:
    type: apiKey
    name: Authorization
    in: header
paths:
  /:
    get:
      tags:
      - "meta"
      summary: "Returns information of the api"
      description: ""
      operationId: "apiInfo"
      produces:
      - "application/json"
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/ApiInfo"
  /auth/register:
    post:
      tags:
      - "auth"
      summary: "Registers a new user"
      description: ""
      operationId: "registerUser"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "User object"
        required: true
        schema:
          $ref: "#/definitions/NewUser"
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/User"
        401:
          description: "Invalid credentials"
  /auth/login:
    post:
      security:
        - basicAuth: []
      tags:
      - "auth"
      summary: "Login a user"
      description: ""
      operationId: "loginUser"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Login response object"
        required: true
        schema:
          $ref: "#/definitions/LoginResponse"
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/LoginResponse"
        401:
          description: "Invalid credentials"
  /auth/reset:
    post:
      tags:
      - "auth"
      summary: "Request to reset password of the given user(email)"
      description: ""
      operationId: "requestToResetPassword"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Reset body"
        required: true
        schema:
          type: object
          required:
          - email
          - host
          properties:
            email:
              type: string
            host:
              type: string
              description: "Path to the used frontend appplication(including protocol)"
      responses:
        200:
          description: "Successful operation"
  /auth/reset/{resetToken}:
    post:
      tags:
      - "auth"
      summary: "Reset password of the given user"
      description: ""
      operationId: "resetPassword"
      produces:
      - "application/json"
      parameters:
      - name: "resetToken"
        in: "path"
        description: "Token to reset the password"
        required: true
        type: "string"
      - in: "body"
        name: "body"
        description: "Password"
        required: true
        schema:
          type: object
          required:
          - password
          properties:
            password:
              type: string
      responses:
        200:
          description: "Successful operation"
        400:
          description: "Invalid password credentials"
  /auth/verify/{verifyToken}:
    put:
      tags:
      - "auth"
      summary: "Verifys the user throw the email address"
      description: ""
      operationId: "verifyEmail"
      produces:
      - "application/json"
      parameters:
      - name: "verifyToken"
        in: "path"
        description: "Token to verify the email and the user"
        required: true
        type: "string"
      responses:
        200:
          description: "Successful operation"
        400:
          description: "Invalid verify token"
  /users/me:
    get:
      security:
        - bearerAuth: []
      tags:
      - "users"
      summary: "Retunrs the currently logged in user"
      description: ""
      operationId: "getMe"
      produces:
      - "application/json"
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/User"
        401:
          description: "Invalid credentials"
  /users:
    get:
      security:
        - bearerAuth: []
      tags:
      - "users"
      summary: "Retunrs a list of users"
      description: ""
      operationId: "getUsers"
      produces:
      - "application/json"
      parameters:
      - name: "filter"
        in: "query"
        description: "The user name or email"
        type: "string"
      responses:
        200:
          description: "Successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/User"
        401:
          description: "Invalid credentials"
  /users/{userId}:
    get:
      security:
        - bearerAuth: []
      tags:
      - "users"
      summary: "Returns the user with the given id"
      description: ""
      operationId: "getUserById"
      produces:
      - "application/json"
      parameters:
      - name: "userId"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/User"
        401:
          description: "Invalid credentials"
        404:
          description: "Not found"
    put:
      security:
        - bearerAuth: []
      tags:
      - "users"
      summary: "Update user"
      description: ""
      operationId: "updateUser"
      produces:
      - "application/json"
      parameters:
      - name: "userId"
        in: "path"
        required: true
        type: "string"
      - in: "body"
        name: "body"
        description: "Updated user object"
        required: true
        schema:
          $ref: "#/definitions/User"
      responses:
        400:
          description: "Invalid user supplied"
        404:
          description: "User not found"
        401:
          description: "Invalid credentials"
        403:
          description: "Only the logged in user can modify himself"
  /teams:
    post:
      security:
        - bearerAuth: []
      tags:
      - "teams"
      summary: "Create team"
      operationId: "createTeam"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Created team object"
        required: true
        schema:
          $ref: "#/definitions/NewTeam"
      responses:
        400:
          description: "Invalid team supplied"
        404:
          description: "Not found"
        401:
          description: "Invalid credentials"
  /teams/{teamId}/uploadAvatar:
    put:
      security:
        - bearerAuth: []
      tags:
      - "teams"
      summary: "Upload team avatar"
      operationId: "uploadTeamAvatar"
      consumes:
      - "multipart/form-data"
      produces:
      - "application/json"
      parameters:
      - name: "teamId"
        in: "path"
        required: true
        type: "string"
      - name: "avatar"
        in: "formData"
        description: "avatar to upload"
        required: true
        type: "file"
      responses:
        400:
          description: "Invalid team supplied"
        404:
          description: "Not found"
        401:
          description: "Invalid credentials"
  /teams/{teamId}/user/{userId}:
    put:
      security:
        - bearerAuth: []
      tags:
      - "teams"
      summary: "Invite user to team"
      description: "Only the team owner has the permission to do that"
      operationId: "inviteUserToTeam"
      produces:
      - "application/json"
      parameters:
      - name: "teamId"
        in: "path"
        required: true
        type: "string"
      - name: "userId"
        in: "path"
        required: true
        type: "string"
      responses:
        400:
          description: "Invalid parameter supplied"
        404:
          description: "Not found"
        401:
          description: "Invalid credentials"
    delete:
      security:
        - bearerAuth: []
      tags:
      - "teams"
      summary: "Remove user from team"
      description: "Only the team owner has the permission to do that and the user who wants to remove himself. Moreover if there are not users left in a team then we have to drop it."
      operationId: "removeUserFromTeam"
      produces:
      - "application/json"
      parameters:
      - name: "teamId"
        in: "path"
        required: true
        type: "string"
      - name: "userId"
        in: "path"
        required: true
        type: "string"
      responses:
        400:
          description: "Invalid parameter supplied"
        404:
          description: "Not found"
        401:
          description: "Invalid credentials"
  /teams/{teamId}/user:
    put:
      security:
        - bearerAuth: []
      tags:
      - "teams"
      summary: "Accept invation to a team"
      description: "Only invited user can perform this"
      operationId: "acceptTeam"
      produces:
      - "application/json"
      parameters:
      - name: "teamId"
        in: "path"
        required: true
        type: "string"
      responses:
        400:
          description: "Invalid parameter supplied"
        404:
          description: "Not found"
        401:
          description: "Invalid credentials"
  /teams/{teamId}:
    get:
      security:
        - bearerAuth: []
      tags:
      - "teams"
      summary: "Returns the team with the given id"
      description: ""
      operationId: "getTeamById"
      produces:
      - "application/json"
      parameters:
      - name: "teamId"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/Team"
        401:
          description: "Invalid credentials"
        404:
          description: "Not found"
    put:
      security:
        - bearerAuth: []
      tags:
      - "teams"
      summary: "Update team"
      description: ""
      operationId: "updateTeam"
      produces:
      - "application/json"
      parameters:
      - name: "teamId"
        in: "path"
        required: true
        type: "string"
      - in: "body"
        name: "body"
        description: "Updated team object"
        required: true
        schema:
          $ref: "#/definitions/Team"
      responses:
        400:
          description: "Invalid team supplied"
        404:
          description: "Not found"
        401:
          description: "Invalid credentials"
  /teams/{teamId}/ranking:
    get:
      security:
        - bearerAuth: []
      tags:
      - "teams"
      summary: "Returns a list of users with their rank and points"
      description: ""
      operationId: "getTeamRanking"
      produces:
      - "application/json"
      parameters:
      - name: "teamId"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: "Successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/UserRanking"
        401:
          description: "Invalid credentials"
        404:
          description: "Not found"
  /game-phases:
    get:
      security:
        - bearerAuth: []
      tags:
      - "games"
      summary: "Returns a list of phases"
      description: ""
      operationId: "getGamePhases"
      produces:
      - "application/json"
      responses:
        200:
          description: "Successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/GamePhase"
        401:
          description: "Invalid credentials"
  /games:
    get:
      security:
        - bearerAuth: []
      tags:
      - "games"
      summary: "Returns a list of games"
      description: ""
      operationId: "getGames"
      produces:
      - "application/json"
      parameters:
      - name: "phaseId"
        in: "query"
        description: "The phase of the game like final"
        type: "string"
      responses:
        200:
          description: "Successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Game"
        401:
          description: "Invalid credentials"
  /games/{gameId}:
    put:
      security:
        - bearerAuth: []
      tags:
      - "games"
      summary: "Update a game"
      description: "Only the admins can to that"
      operationId: "modifyGames"
      produces:
      - "application/json"
      parameters:
      - name: "gameId"
        in: "path"
        required: true
        type: "string"
      - in: "body"
        name: "body"
        description: "Updated team object"
        required: true
        schema:
          $ref: "#/definitions/Game"
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/Game"
        401:
          description: "Invalid credentials"
  /games/{gameId}/tip:
    post:
      security:
        - bearerAuth: []
      tags:
      - "games"
      summary: "Enter tip of game"
      description: ""
      operationId: "tipGame"
      produces:
      - "application/json"
      parameters:
      - name: "gameId"
        in: "path"
        required: true
        type: "string"
      - name: "userId"
        in: "query"
        required: false
        type: "string"
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/NewTip"
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/NewTip"
        400:
          description: "Invalid tip"
        401:
          description: "Invalid credentials"
        404:
          description: "Not found"
  /ranking/users:
    get:
      security:
        - bearerAuth: []
      tags:
      - "ranking"
      summary: "Returns a list of users with their points"
      description: ""
      operationId: "getUsersRanking"
      produces:
      - "application/json"
      responses:
        200:
          description: "Successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/UserRanking"
        401:
          description: "Invalid credentials"
  /ranking/teams:
    get:
      security:
        - bearerAuth: []
      tags:
      - "ranking"
      summary: "Returns a list of teams with their points"
      description: ""
      operationId: "getTeamsRanking"
      produces:
      - "application/json"
      responses:
        200:
          description: "Successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/TeamRanking"
        401:
          description: "Invalid credentials"
definitions:
  ApiInfo:
    type: "object"
    properties:
      name:
        type: "string"
      version:
        type: "string"
  LoginResponse:
    type: "object"
    properties:
      accessToken:
        type: "string"
  User:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      username:
        type: "string"
      email:
        type: "string"
  NewUser:
    type: "object"
    properties:
      username:
        type: "string"
      email:
        type: "string"
      password:
        type: "string"
  Team:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
      avatarUrl:
        type: "string"
  NewTeam:
    type: "object"
    properties:
      name:
        type: "string"
  UserRanking:
    type: "object"
    properties:
      rank:
        type: "integer"
        format: "int64"
      user:
        $ref: "#/definitions/User"
      points:
        type: "integer"
        format: "int64"
  TeamRanking:
    type: "object"
    properties:
      rank:
        type: "integer"
        format: "int64"
      team:
        $ref: "#/definitions/Team"
      points:
        type: "integer"
        format: "int64"
  GameNation:
    type: "object"
    properties:
      nation:
        $ref: "#/definitions/Nation"
      score:
        type: "integer"
        format: "int64"
  Tip:
    type: "object"
    properties:
      hostScore:
        type: "integer"
        format: "int64"
      guestScore:
        type: "integer"
        format: "int64"
      rules:
        type: "array"
        items:
          $ref: "#/definitions/Rule"
  NewTip:
    type: "object"
    properties:
      hostScore:
        type: "integer"
        format: "int64"
      guestScore:
        type: "integer"
        format: "int64"
  Rule:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      description:
        type: "string"
      points:
        type: "integer"
        format: "int64"
  Nation:
    type: "object"
    properties:
      id:
        type: "string"
      name:
        type: "string"
  Stadium:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
  GamePhase:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
  Game:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      date:
        type: "string"
        format: "date-time"
      phaseId:
        type: "integer"
        format: "int64"
      stadium:
        $ref: "#/definitions/Stadium"
      host:
        $ref: "#/definitions/GameNation"
      guest:
        $ref: "#/definitions/GameNation"
      tip:
        $ref: "#/definitions/Tip"